<?php 
require('../fpdf/fpdf.php');
	$pdf = new FPDF();
	$pdf->AddPage();
	$pdf->SetFont("Arial", "", 12);
	$pdf->Cell(0,0,"SOMMAIRE",0,0,C);
	$pdf->Text(10,25,"Title 1 ");
	$pdf->Text(20,30,"Title 2 ");
	$pdf->Text(30,35,"Title 3 ");
	$pdf->Text(20,40,"Titre super ");
	$pdf->Text(10,45,"Title Great ");
	$pdf->Text(20,50,"Title super ");
	$pdf->AddPage();
	$pdf->SetFont("Arial", "B", 32);
	$pdf->SetXY(0, 30);
	$pdf->Cell(0,0,"SAMPLE DOC Oumar Exe ",0,0,C);
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetTextColor(130, 0, 0);
	$pdf->Text(10,45,"Title 1 ");
	$pdf->SetTextColor(0);
	$pdf->SetTextColor(0, 130, 0);
	$pdf->Text(20,50,"Title 2 ");
	$pdf->SetTextColor(0);
	$pdf->SetTextColor(20, 20, 130);
	$pdf->Text(30,55,"Title 3 ");
	$pdf->SetTextColor(0);
	$pdf->SetXY(10, 60);
	$pdf->Text(10,60,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,60,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,60," Fin de texte darktsar");
	$pdf->SetXY(10, 65);
	$pdf->SetFont("Arial", "I", 12);
	$pdf->Text(10,65,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetTextColor(0, 130, 0);
	$pdf->Text(20,70,"Titre super ");
	$pdf->SetTextColor(0);
	$pdf->SetXY(10, 75);
	$pdf->Text(10,75,"Je teste le underline ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Je teste le underline "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "U", 12);
	$pdf->Text($cordX,75,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,75," bonne fin");
	$pdf->SetXY(10, 80);
	$pdf->Text(10,80,"Bonjour Moussa Doumbouya ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Bonjour Moussa Doumbouya "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "BI", 12);
	$pdf->Text($cordX,80,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,80," c super non");
	$pdf->SetXY(10, 85);
	$pdf->Text(10,85,"Bonjour Moussa Doumbouya ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Bonjour Moussa Doumbouya "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "BI", 12);
	$pdf->Text($cordX,85,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,85," c super non");
	$pdf->SetXY(10, 90);
	$pdf->Text(10,90,"Bonjour Moussa Doumbouya ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Bonjour Moussa Doumbouya "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "BI", 12);
	$pdf->Text($cordX,90,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,90," c super non");
	$pdf->SetXY(10, 95);
	$pdf->Text(10,95,"Bonjour Moussa Doumbouya ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Bonjour Moussa Doumbouya "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "BI", 12);
	$pdf->Text($cordX,95,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,95," c super non");
	$pdf->SetXY(10, 100);
	$pdf->Text(10,100,"Bonjour Moussa Doumbouya ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Bonjour Moussa Doumbouya "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "BI", 12);
	$pdf->Text($cordX,100,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,100," c super non");
	$pdf->SetXY(10, 110);
	$pdf->Text(10,110,"Bonjour Moussa Doumbouya ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Bonjour Moussa Doumbouya "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "BI", 12);
	$pdf->Text($cordX,110,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,110," c super non");
	$pdf->SetXY(10, 115);
	$pdf->Text(10,115,"Bonjour Moussa Doumbouya ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Bonjour Moussa Doumbouya "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "BI", 12);
	$pdf->Text($cordX,115,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,115," c super non");
	$pdf->SetXY(10, 120);
	$pdf->Text(10,120,"Bonjour Moussa Doumbouya ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("Bonjour Moussa Doumbouya "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "BI", 12);
	$pdf->Text($cordX,120,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,120," c super non");
	$pdf->SetXY(10, 125);
	$pdf->Text(10,125,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,125,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,125," Fin de texte darktsar");
	$pdf->SetXY(10, 130);
	$pdf->Text(10,130,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,130,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,130," Fin de texte darktsar");
	$pdf->SetXY(10, 135);
	$pdf->Text(10,135,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,135,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,135," Fin de texte darktsar");
	$pdf->SetXY(10, 140);
	$pdf->Text(10,140,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,140,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,140," Fin de texte darktsar");
	$pdf->SetXY(10, 150);
	$pdf->Text(10,150,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,150,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,150," Fin de texte darktsar");
	$pdf->SetXY(10, 155);
	$pdf->Text(10,155,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,155,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,155," Fin de texte darktsar");
	$pdf->SetXY(10, 160);
	$pdf->Text(10,160,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,160,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,160," Fin de texte darktsar");
	$pdf->SetXY(10, 170);
	$pdf->Text(10,170,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,170,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,170," Fin de texte darktsar");
	$pdf->SetXY(10, 175);
	$pdf->Text(10,175,"BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("BONJOUR COUCOU GRAND Darktsar Oumar Exe TRAORE  "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,175,"SAMPLE ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("SAMPLE ")) + 18 + $cordX;
	$pdf->Text($cordX,175," Fin de texte darktsar");
	$pdf->SetXY(10, 180);
	$pdf->SetFont("Arial", "BU", 12);
	$pdf->Text(10,180,"SAMPLE");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetTextColor(130, 0, 0);
	$pdf->Text(10,185,"Title Great ");
	$pdf->SetTextColor(0);
	$pdf->SetXY(10, 190);
	$pdf->SetFont("Arial", "BIU", 12);
	$pdf->Text(10,190,"SAMPLE");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetTextColor(0, 130, 0);
	$pdf->Text(20,195,"Title super ");
	$pdf->SetTextColor(0);
	$pdf->SetXY(10, 200);
	$pdf->Text(10,200,"General de l'arme ");
	$cordX = $pdf->SetX($pdf->GetStringWidth("General de l'arme "));
	$cordX = $pdf->GetX() + 9;
	$pdf->SetFont("Arial", "B", 12);
	$pdf->Text($cordX,200,"MARGI ");
	$pdf->SetFont("Arial", "", 12);
	$pdf->SetFont("Arial", "", 12);
	$cordX = $pdf->SetX($pdf->GetStringWidth("MARGI ")) + 18 + $cordX;
	$pdf->Text($cordX,200," Coucou Grand");
	$pdf->Text(10,205,"color:#12345/ TEXT_COLORED /:color
");
	$pdf->AddPage();
	$pdf->AddPage();
	$pdf->SetXY(0, 20);
	$pdf->Cell(0,0,"Table of Content",0,0,C);
	$pdf->Text(10,35,"Title 1 ");
	$pdf->Text(20,40,"Title 2 ");
	$pdf->Text(30,45,"Title 3 ");
	$pdf->Text(20,50,"Titre super ");
	$pdf->Text(10,55,"Title Great ");
	$pdf->Text(20,60,"Title super ");
	$pdf->AddPage();
	$pdf->Text(10,25,"Du contenu san style
");
	$pdf->Text(10,30,"
");
	$pdf->Text(10,35,"");
	$pdf->Output();
?>